[package]
name = "grovedbg"
authors = ["Evgeny Fomin <evgeny.fomin@dash.org>"]
version = "0.1.0"
description = "GroveDB inspection tool"
edition = "2021"

[dependencies]
eframe = "0.26.2"
env_logger = "0.11.3"
