[package]
name = "grovedbg"
authors = ["Evgeny Fomin <evgeny.fomin@dash.org>"]
version = "0.1.0"
description = "GroveDB inspection tool"
edition = "2021"

[dependencies]
eframe = "0.26.2"
egui-snarl = "0.3.0"
env_logger = "0.11.3"
grovedbg-grpc = { path = "../grovedb/grovedbg-grpc/"}
hex = "0.4.3"
slab = "0.4.9"
tokio = { version = "1.36.0", features = ["full"] }
